---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-team
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Africa-Can-Do/qa-repo
